apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    argocd-image-updater.argoproj.io/image-list: argo=kamalfarah/argo
    argocd-image-updater.argoproj.io/hello-nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/hello-nginx.allow-tags: regexp:^\d+$
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: kamalfarah/argo:v1.0
          ports:
            - containerPort: 80


